<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class CreateCountriesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('country');
            $table->string('code')->nullable();
            $table->string('countrycode')->nullable();            
            $table->timestamps();
        });

        $this->Insert();
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('countries');
    }

    // Insert Countries Data
    public function Insert(){
        DB::statement("
            INSERT INTO `countries` (`id`, `country`, `code`, `countrycode`, `created_at`, `updated_at`) VALUES
            (1, 'Afghanistan', 'AF', 'AFG', NULL, NULL),
            (2, 'Aland Islands', 'AX', 'ALA', NULL, NULL),
            (3, 'Albania', 'AL', 'ALB', NULL, NULL),
            (4, 'Algeria', 'DZ', 'DZA', NULL, NULL),
            (5, 'American Samoa', 'AS', 'ASM', NULL, NULL),
            (6, 'Andorra', 'AD', 'AND', NULL, NULL),
            (7, 'Angola', 'AO', 'AGO', NULL, NULL),
            (8, 'Anguilla', 'AI', 'AIA', NULL, NULL),
            (9, 'Antarctica', 'AQ', 'ATA', NULL, NULL),
            (10, 'Antigua and Barbuda', 'AG', 'ATG', NULL, NULL),
            (11, 'Argentina', 'AR', 'ARG', NULL, NULL),
            (12, 'Armenia', 'AM', 'ARM', NULL, NULL),
            (13, 'Aruba', 'AW', 'ABW', NULL, NULL),
            (14, 'Australia', 'AU', 'AUS', NULL, NULL),
            (15, 'Austria', 'AT', 'AUT', NULL, NULL),
            (16, 'Azerbaijan', 'AZ', 'AZE', NULL, NULL),
            (17, 'Bahamas', 'BS', 'BHS', NULL, NULL),
            (18, 'Bahrain', 'BH', 'BHR', NULL, NULL),
            (19, 'Bangladesh', 'BD', 'BGD', NULL, NULL),
            (20, 'Barbados', 'BB', 'BRB', NULL, NULL),
            (21, 'Belarus', 'BY', 'BLR', NULL, NULL),
            (22, 'Belgium', 'BE', 'BEL', NULL, NULL),
            (23, 'Belize', 'BZ', 'BLZ', NULL, NULL),
            (24, 'Benin', 'BJ', 'BEN', NULL, NULL),
            (25, 'Bermuda', 'BM', 'BMU', NULL, NULL),
            (26, 'Bhutan', 'BT', 'BTN', NULL, NULL),
            (27, 'Bolivia', 'BO', 'BOL', NULL, NULL),
            (28, 'Bonaire, Sint Eustatius and Saba', 'BQ', 'BES', NULL, NULL),
            (29, 'Bosnia and Herzegovina', 'BA', 'BIH', NULL, NULL),
            (30, 'Botswana', 'BW', 'BWA', NULL, NULL),
            (31, 'Bouvet Island', 'BV', 'BVT', NULL, NULL),
            (32, 'Brazil', 'BR', 'BRA', NULL, NULL),
            (33, 'British Indian Ocean Territory', 'IO', 'IOT', NULL, NULL),
            (34, 'Brunei', 'BN', 'BRN', NULL, NULL),
            (35, 'Bulgaria', 'BG', 'BGR', NULL, NULL),
            (36, 'Burkina Faso', 'BF', 'BFA', NULL, NULL),
            (37, 'Burundi', 'BI', 'BDI', NULL, NULL),
            (38, 'Cambodia', 'KH', 'KHM', NULL, NULL),
            (39, 'Cameroon', 'CM', 'CMR', NULL, NULL),
            (40, 'Canada', 'CA', 'CAN', NULL, NULL),
            (41, 'Cape Verde', 'CV', 'CPV', NULL, NULL),
            (42, 'Cayman Islands', 'KY', 'CYM', NULL, NULL),
            (43, 'Central African Republic', 'CF', 'CAF', NULL, NULL),
            (44, 'Chad', 'TD', 'TCD', NULL, NULL),
            (45, 'Chile', 'CL', 'CHL', NULL, NULL),
            (46, 'China', 'CN', 'CHN', NULL, NULL),
            (47, 'Christmas Island', 'CX', 'CXR', NULL, NULL),
            (48, 'Cocos (Keeling) Islands', 'CC', 'CCK', NULL, NULL),
            (49, 'Colombia', 'CO', 'COL', NULL, NULL),
            (50, 'Comoros', 'KM', 'COM', NULL, NULL),
            (51, 'Congo', 'CG', 'COG', NULL, NULL),
            (52, 'Cook Islands', 'CK', 'COK', NULL, NULL),
            (53, 'Costa Rica', 'CR', 'CRI', NULL, NULL),
            (54, 'Ivory Coast', 'CI', 'CIV', NULL, NULL),
            (55, 'Croatia', 'HR', 'HRV', NULL, NULL),
            (56, 'Cuba', 'CU', 'CUB', NULL, NULL),
            (57, 'Curacao', 'CW', 'CUW', NULL, NULL),
            (58, 'Cyprus', 'CY', 'CYP', NULL, NULL),
            (59, 'Czech Republic', 'CZ', 'CZE', NULL, NULL),
            (60, 'Democratic Republic of the Congo', 'CD', 'COD', NULL, NULL),
            (61, 'Denmark', 'DK', 'DNK', NULL, NULL),
            (62, 'Djibouti', 'DJ', 'DJI', NULL, NULL),
            (63, 'Dominica', 'DM', 'DMA', NULL, NULL),
            (64, 'Dominican Republic', 'DO', 'DOM', NULL, NULL),
            (65, 'Ecuador', 'EC', 'ECU', NULL, NULL),
            (66, 'Egypt', 'EG', 'EGY', NULL, NULL),
            (67, 'El Salvador', 'SV', 'SLV', NULL, NULL),
            (68, 'Equatorial Guinea', 'GQ', 'GNQ', NULL, NULL),
            (69, 'Eritrea', 'ER', 'ERI', NULL, NULL),
            (70, 'Estonia', 'EE', 'EST', NULL, NULL),
            (71, 'Ethiopia', 'ET', 'ETH', NULL, NULL),
            (72, 'Falkland Islands (Malvinas)', 'FK', 'FLK', NULL, NULL),
            (73, 'Faroe Islands', 'FO', 'FRO', NULL, NULL),
            (74, 'Fiji', 'FJ', 'FJI', NULL, NULL),
            (75, 'Finland', 'FI', 'FIN', NULL, NULL),
            (76, 'France', 'FR', 'FRA', NULL, NULL),
            (77, 'French Guiana', 'GF', 'GUF', NULL, NULL),
            (78, 'French Polynesia', 'PF', 'PYF', NULL, NULL),
            (79, 'French Southern Territories', 'TF', 'ATF', NULL, NULL),
            (80, 'Gabon', 'GA', 'GAB', NULL, NULL),
            (81, 'Gambia', 'GM', 'GMB', NULL, NULL),
            (82, 'Georgia', 'GE', 'GEO', NULL, NULL),
            (83, 'Germany', 'DE', 'DEU', NULL, NULL),
            (84, 'Ghana', 'GH', 'GHA', NULL, NULL),
            (85, 'Gibraltar', 'GI', 'GIB', NULL, NULL),
            (86, 'Greece', 'GR', 'GRC', NULL, NULL),
            (87, 'Greenland', 'GL', 'GRL', NULL, NULL),
            (88, 'Grenada', 'GD', 'GRD', NULL, NULL),
            (89, 'Guadaloupe', 'GP', 'GLP', NULL, NULL),
            (90, 'Guam', 'GU', 'GUM', NULL, NULL),
            (91, 'Guatemala', 'GT', 'GTM', NULL, NULL),
            (92, 'Guernsey', 'GG', 'GGY', NULL, NULL),
            (93, 'Guinea', 'GN', 'GIN', NULL, NULL),
            (94, 'Guinea-Bissau', 'GW', 'GNB', NULL, NULL),
            (95, 'Guyana', 'GY', 'GUY', NULL, NULL),
            (96, 'Haiti', 'HT', 'HTI', NULL, NULL),
            (97, 'Heard Island and McDonald Islands', 'HM', 'HMD', NULL, NULL),
            (98, 'Honduras', 'HN', 'HND', NULL, NULL),
            (99, 'Hong Kong', 'HK', 'HKG', NULL, NULL),
            (100, 'Hungary', 'HU', 'HUN', NULL, NULL),
            (101, 'Iceland', 'IS', 'ISL', NULL, NULL),
            (102, 'India', 'IN', 'IND', NULL, NULL),
            (103, 'Indonesia', 'ID', 'IDN', NULL, NULL),
            (104, 'Iran', 'IR', 'IRN', NULL, NULL),
            (105, 'Iraq', 'IQ', 'IRQ', NULL, NULL),
            (106, 'Ireland', 'IE', 'IRL', NULL, NULL),
            (107, 'Isle of Man', 'IM', 'IMN', NULL, NULL),
            (108, 'Israel', 'IL', 'ISR', NULL, NULL),
            (109, 'Italy', 'IT', 'ITA', NULL, NULL),
            (110, 'Jamaica', 'JM', 'JAM', NULL, NULL),
            (111, 'Japan', 'JP', 'JPN', NULL, NULL),
            (112, 'Jersey', 'JE', 'JEY', NULL, NULL),
            (113, 'Jordan', 'JO', 'JOR', NULL, NULL),
            (114, 'Kazakhstan', 'KZ', 'KAZ', NULL, NULL),
            (115, 'Kenya', 'KE', 'KEN', NULL, NULL),
            (116, 'Kiribati', 'KI', 'KIR', NULL, NULL),
            (117, 'Kosovo', 'XK', '---', NULL, NULL),
            (118, 'Kuwait', 'KW', 'KWT', NULL, NULL),
            (119, 'Kyrgyzstan', 'KG', 'KGZ', NULL, NULL),
            (120, 'Laos', 'LA', 'LAO', NULL, NULL),
            (121, 'Latvia', 'LV', 'LVA', NULL, NULL),
            (122, 'Lebanon', 'LB', 'LBN', NULL, NULL),
            (123, 'Lesotho', 'LS', 'LSO', NULL, NULL),
            (124, 'Liberia', 'LR', 'LBR', NULL, NULL),
            (125, 'Libya', 'LY', 'LBY', NULL, NULL),
            (126, 'Liechtenstein', 'LI', 'LIE', NULL, NULL),
            (127, 'Lithuania', 'LT', 'LTU', NULL, NULL),
            (128, 'Luxembourg', 'LU', 'LUX', NULL, NULL),
            (129, 'Macao', 'MO', 'MAC', NULL, NULL),
            (130, 'Macedonia', 'MK', 'MKD', NULL, NULL),
            (131, 'Madagascar', 'MG', 'MDG', NULL, NULL),
            (132, 'Malawi', 'MW', 'MWI', NULL, NULL),
            (133, 'Malaysia', 'MY', 'MYS', NULL, NULL),
            (134, 'Maldives', 'MV', 'MDV', NULL, NULL),
            (135, 'Mali', 'ML', 'MLI', NULL, NULL),
            (136, 'Malta', 'MT', 'MLT', NULL, NULL),
            (137, 'Marshall Islands', 'MH', 'MHL', NULL, NULL),
            (138, 'Martinique', 'MQ', 'MTQ', NULL, NULL),
            (139, 'Mauritania', 'MR', 'MRT', NULL, NULL),
            (140, 'Mauritius', 'MU', 'MUS', NULL, NULL),
            (141, 'Mayotte', 'YT', 'MYT', NULL, NULL),
            (142, 'Mexico', 'MX', 'MEX', NULL, NULL),
            (143, 'Micronesia', 'FM', 'FSM', NULL, NULL),
            (144, 'Moldava', 'MD', 'MDA', NULL, NULL),
            (145, 'Monaco', 'MC', 'MCO', NULL, NULL),
            (146, 'Mongolia', 'MN', 'MNG', NULL, NULL),
            (147, 'Montenegro', 'ME', 'MNE', NULL, NULL),
            (148, 'Montserrat', 'MS', 'MSR', NULL, NULL),
            (149, 'Morocco', 'MA', 'MAR', NULL, NULL),
            (150, 'Mozambique', 'MZ', 'MOZ', NULL, NULL),
            (151, 'Myanmar (Burma)', 'MM', 'MMR', NULL, NULL),
            (152, 'Namibia', 'NA', 'NAM', NULL, NULL),
            (153, 'Nauru', 'NR', 'NRU', NULL, NULL),
            (154, 'Nepal', 'NP', 'NPL', NULL, NULL),
            (155, 'Netherlands', 'NL', 'NLD', NULL, NULL),
            (156, 'New Caledonia', 'NC', 'NCL', NULL, NULL),
            (157, 'New Zealand', 'NZ', 'NZL', NULL, NULL),
            (158, 'Nicaragua', 'NI', 'NIC', NULL, NULL),
            (159, 'Niger', 'NE', 'NER', NULL, NULL),
            (160, 'Nigeria', 'NG', 'NGA', NULL, NULL),
            (161, 'Niue', 'NU', 'NIU', NULL, NULL),
            (162, 'Norfolk Island', 'NF', 'NFK', NULL, NULL),
            (163, 'North Korea', 'KP', 'PRK', NULL, NULL),
            (164, 'Northern Mariana Islands', 'MP', 'MNP', NULL, NULL),
            (165, 'Norway', 'NO', 'NOR', NULL, NULL),
            (166, 'Oman', 'OM', 'OMN', NULL, NULL),
            (167, 'Pakistan', 'PK', 'PAK', NULL, NULL),
            (168, 'Palau', 'PW', 'PLW', NULL, NULL),
            (169, 'Palestine', 'PS', 'PSE', NULL, NULL),
            (170, 'Panama', 'PA', 'PAN', NULL, NULL),
            (171, 'Papua New Guinea', 'PG', 'PNG', NULL, NULL),
            (172, 'Paraguay', 'PY', 'PRY', NULL, NULL),
            (173, 'Peru', 'PE', 'PER', NULL, NULL),
            (174, 'Phillipines', 'PH', 'PHL', NULL, NULL),
            (175, 'Pitcairn', 'PN', 'PCN', NULL, NULL),
            (176, 'Poland', 'PL', 'POL', NULL, NULL),
            (177, 'Portugal', 'PT', 'PRT', NULL, NULL),
            (178, 'Puerto Rico', 'PR', 'PRI', NULL, NULL),
            (179, 'Qatar', 'QA', 'QAT', NULL, NULL),
            (180, 'Reunion', 'RE', 'REU', NULL, NULL),
            (181, 'Romania', 'RO', 'ROU', NULL, NULL),
            (182, 'Russia', 'RU', 'RUS', NULL, NULL),
            (183, 'Rwanda', 'RW', 'RWA', NULL, NULL),
            (184, 'Saint Barthelemy', 'BL', 'BLM', NULL, NULL),
            (185, 'Saint Helena', 'SH', 'SHN', NULL, NULL),
            (186, 'Saint Kitts and Nevis', 'KN', 'KNA', NULL, NULL),
            (187, 'Saint Lucia', 'LC', 'LCA', NULL, NULL),
            (188, 'Saint Martin', 'MF', 'MAF', NULL, NULL),
            (189, 'Saint Pierre and Miquelon', 'PM', 'SPM', NULL, NULL),
            (190, 'Saint Vincent and the Grenadines', 'VC', 'VCT', NULL, NULL),
            (191, 'Samoa', 'WS', 'WSM', NULL, NULL),
            (192, 'San Marino', 'SM', 'SMR', NULL, NULL),
            (193, 'Sao Tome and Principe', 'ST', 'STP', NULL, NULL),
            (194, 'Saudi Arabia', 'SA', 'SAU', NULL, NULL),
            (195, 'Senegal', 'SN', 'SEN', NULL, NULL),
            (196, 'Serbia', 'RS', 'SRB', NULL, NULL),
            (197, 'Seychelles', 'SC', 'SYC', NULL, NULL),
            (198, 'Sierra Leone', 'SL', 'SLE', NULL, NULL),
            (199, 'Singapore', 'SG', 'SGP', NULL, NULL),
            (200, 'Sint Maarten', 'SX', 'SXM', NULL, NULL),
            (201, 'Slovakia', 'SK', 'SVK', NULL, NULL),
            (202, 'Slovenia', 'SI', 'SVN', NULL, NULL),
            (203, 'Solomon Islands', 'SB', 'SLB', NULL, NULL),
            (204, 'Somalia', 'SO', 'SOM', NULL, NULL),
            (205, 'South Africa', 'ZA', 'ZAF', NULL, NULL),
            (206, 'South Georgia and the South Sandwich Islands', 'GS', 'SGS', NULL, NULL),
            (207, 'South Korea', 'KR', 'KOR', NULL, NULL),
            (208, 'South Sudan', 'SS', 'SSD', NULL, NULL),
            (209, 'Spain', 'ES', 'ESP', NULL, NULL),
            (210, 'Sri Lanka', 'LK', 'LKA', NULL, NULL),
            (211, 'Sudan', 'SD', 'SDN', NULL, NULL),
            (212, 'Suriname', 'SR', 'SUR', NULL, NULL),
            (213, 'Svalbard and Jan Mayen', 'SJ', 'SJM', NULL, NULL),
            (214, 'Swaziland', 'SZ', 'SWZ', NULL, NULL),
            (215, 'Sweden', 'SE', 'SWE', NULL, NULL),
            (216, 'Switzerland', 'CH', 'CHE', NULL, NULL),
            (217, 'Syria', 'SY', 'SYR', NULL, NULL),
            (218, 'Taiwan', 'TW', 'TWN', NULL, NULL),
            (219, 'Tajikistan', 'TJ', 'TJK', NULL, NULL),
            (220, 'Tanzania', 'TZ', 'TZA', NULL, NULL),
            (221, 'Thailand', 'TH', 'THA', NULL, NULL),
            (222, 'Timor-Leste (East Timor)', 'TL', 'TLS', NULL, NULL),
            (223, 'Togo', 'TG', 'TGO', NULL, NULL),
            (224, 'Tokelau', 'TK', 'TKL', NULL, NULL),
            (225, 'Tonga', 'TO', 'TON', NULL, NULL),
            (226, 'Trinidad and Tobago', 'TT', 'TTO', NULL, NULL),
            (227, 'Tunisia', 'TN', 'TUN', NULL, NULL),
            (228, 'Turkey', 'TR', 'TUR', NULL, NULL),
            (229, 'Turkmenistan', 'TM', 'TKM', NULL, NULL),
            (230, 'Turks and Caicos Islands', 'TC', 'TCA', NULL, NULL),
            (231, 'Tuvalu', 'TV', 'TUV', NULL, NULL),
            (232, 'Uganda', 'UG', 'UGA', NULL, NULL),
            (233, 'Ukraine', 'UA', 'UKR', NULL, NULL),
            (234, 'United Arab Emirates', 'AE', 'ARE', NULL, NULL),
            (235, 'United Kingdom', 'GB', 'GBR', NULL, NULL),
            (236, 'United States', 'US', 'USA', NULL, NULL),
            (237, 'United States Minor Outlying Islands', 'UM', 'UMI', NULL, NULL),
            (238, 'Uruguay', 'UY', 'URY', NULL, NULL),
            (239, 'Uzbekistan', 'UZ', 'UZB', NULL, NULL),
            (240, 'Vanuatu', 'VU', 'VUT', NULL, NULL),
            (241, 'Vatican City', 'VA', 'VAT', NULL, NULL),
            (242, 'Venezuela', 'VE', 'VEN', NULL, NULL),
            (243, 'Vietnam', 'VN', 'VNM', NULL, NULL),
            (244, 'Virgin Islands, British', 'VG', 'VGB', NULL, NULL),
            (245, 'Virgin Islands, US', 'VI', 'VIR', NULL, NULL),
            (246, 'Wallis and Futuna', 'WF', 'WLF', NULL, NULL),
            (247, 'Western Sahara', 'EH', 'ESH', NULL, NULL),
            (248, 'Yemen', 'YE', 'YEM', NULL, NULL),
            (249, 'Zambia', 'ZM', 'ZMB', NULL, NULL),
            (250, 'Zimbabwe', 'ZW', 'ZWE', NULL, NULL);"
        );
    }
}
